### ISSUE TITLE
why no download more?

### ISSUE THREAD

**Issue by holygoth** [MicrosoftDocs/windows-iotcore-docs#446] opened 2018-06-17 07:43 UTC
Why no download more???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e816c04b-7c8c-dc54-6382-7c7f2ba532c0
* Version Independent ID: 0e949478-2401-c768-49c6-b21d01d80aa3
* Content: [Get Started Overview - Windows IoT](https://docs.microsoft.com/en-us/windows/iot-core/tutorials/tutorials)
* Content Source: [windows-iotcore/tutorials/Tutorials.md](https://github.com/MicrosoftDocs/windows-iotcore-docs/blob/master/windows-iotcore/tutorials/Tutorials.md)
* Product: **windows-iot**
* GitHub Login: @saraclay
* Microsoft Alias: **saclayt**

**Comment by cyberh0me** [comment] 2018-06-18 22:19
@holygoth can you clarify the actual issue here as the problem is not clear?

**Comment by saraclay** [comment] 2018-06-27 00:18
Closing this due to ambiguity.

**Closed by saraclay** 2018-06-27 00:18 UTC
